---
title: "R Notebook"
output: html_notebook
---

```{r}
library(readr)
library(tidyverse)
library(sf)
library(sp)
library(viridis)
library(tigris)
options(tigris_use_cache = T)
```

# Load Data and Add Census Tracts

```{r}
df = read_csv("Final_Cleaned_Data.csv", col_types = cols(GEOID = "c"))
dc_tracts = tracts(state = "DC", cb = T, year = 2022)

df = left_join(df, dc_tracts %>%
                 select(c(GEOID, geometry, ALAND, AWATER)), by = "GEOID")
```

```{r}
names(df)
```

# Plot Data

```{r}
plot_df = df %>%
  select(c(GEOID, geometry,
           TRACT_COUNT_Public_House)) 
# %>% mutate(dist_to_m_Independen = (1 / (dist_to_m_Independen + 0.001)))
  # %>% mutate(dist_to_m_Independen = 1 - dist_to_m_Independen) #Inverting the Index

ggplot(data = plot_df) + 
  geom_sf(aes(geometry = geometry, fill = 
                # rowMeans(select(plot_df, c(m1_1_sch_1, m1_2_qua_1, dist_to_m_Independen)))
                TRACT_COUNT_Public_House
                ), color = NA) + 
  scale_fill_viridis(alpha = 0.8) +
  labs(title = "Driver 2: Housing", 
       subtitle = "Percentile",
       y = "Longitude", x = "Latitude",
       fill = "Housing")

ggsave("./Plots/Driver 2: Housing.png")
```


