---
title: "R Notebook"
output: html_notebook
---

```{r}
library(readr)
library(tidyverse)
library(sf)
library(sp)
library(viridis)
library(tigris)
options(tigris_use_cache = T)
```

# Load Data and Add Census Tracts

```{r}
df = read_csv("Final_Cleaned_Data.csv", col_types = cols(GEOID = "c"))
dc_tracts = tracts(state = "DC", cb = T, year = 2022)

df = left_join(df, dc_tracts %>%
                 select(c(GEOID, geometry, ALAND, AWATER)), by = "GEOID")
```

```{r}
summary(df)
```

```{r}
df_sf = st_as_sf(df)
df_sf$centroids = st_centroid(df_sf$geometry)
```

# Plot Data

```{r}
ggplot(data = df_sf) + 
  geom_sf(aes(geometry = geometry, fill = dist_to_m_Metro_Stat), color = NA) + 
  geom_sf(aes(geometry = centroids, size = CASTHMA), color = "black", alpha = 0.4) + 
  scale_fill_viridis(alpha = 0.9) +
  labs(title = "Plot of Distance to Metro Stations", 
       subtitle = "Percentile",
       y = "Longitude", x = "Latitude",
       fill = "Distance",
       size = "Asthma")
```

```{r}
library(plotly)
p = ggplot(data = df_sf) + 
  geom_sf(aes(geometry = geometry, fill = dist_to_m_Metro_Stat), color = NA) + 
  geom_sf(aes(geometry = centroids, size = CASTHMA), color = "black", alpha = 0.4) + 
  scale_fill_viridis(alpha = 0.9) +
  labs(title = "Plot of Distance to Metro Stations", 
       subtitle = "Percentile",
       y = "Longitude", x = "Latitude",
       fill = "Distance",
       size = "Asthma")

ggplotly(p)
```

## Plot Individual Indexes

```{r}
names = names(df[, -c(1, ncol(df))])
for(i in 1:(ncol(df) - 2)) {
  plot = ggplot(data = df) +
    geom_sf(aes(geometry = geometry, fill = !!sym(names[i])), col = NA) + 
    scale_fill_viridis(alpha = 0.9) + 
    labs(x = "Latitude", y = "Longitude",
         title = paste("Plot of", names[i]),
         subtitle = "Percentile")
  ggsave(plot = plot, paste("./plots/", names[i], ".png", sep = ""))
}
```
